### PR TITLE
update to new atom version, '.editor depricated

### PR DESCRIPTION
**Pull request by dalexj**

### CODE REVIEW

**Comment by JoshCheek** [comment]
Looks like the leading dot needs to be removed. It appears to be an element rather than a class:

screenshot 2015-01-20 22 43 15

**Comment by dalexj** [comment]
ah yes. Changed accordingly

**Comment by JoshCheek** [comment]
Ty ^_^

**Comment by jesperronn** [comment]
@JoshCheek, I can see the pull request here is merged. But my editor package is not updated. Any additional steps beyond your control which needs to be done to push the changes/version/whatever?

**Comment by JoshCheek** [comment]
Yeah, there were a number of updates. SiB is making some deprecated calls (though this doesn't prevent it from working), and the configuration is completely different now. The new configuration is potentially much much better, so I was initially excited that a whole series of frustrations would simply vanish, for both users and for me. But for several compounding reasons, it hasn't been as easy as one would like, so I've spent an unexpectedly large number of hours of my life over the last couple of days trying to get it working. 

I've got 2 issues on their forum if you're interested in more detail:

* https://discuss.atom.io/t/config-vars-of-type-object-get-lost-ignore-schema/14497/4
* https://discuss.atom.io/t/configuration-vars-dont-show-up/14480

I'm pretty sure I'm just stuck on a bug, though. So, to get it working, I might just keep it on a branch for a few months and come back to see if the situation's improved. I'm interested in getting the integration to a good place, but I spent [a lot of time](https://github.com/JoshCheek/seeing_is_believing/compare/956bd0c...master) on SiB itself this month, and need to allocate the remaining time to other projects.

**Comment by jesperronn** [comment]
wow, I didn't realize there was that much work in it from your side. Fully understand your priorities. So the change in this PR is apparently just the tip of the iceberg...

BTW thanks for your effort, I really appreciate it :)

**Comment by JoshCheek** [comment]
Went ahead and just released it so that at least it won't be broken, and I can set it out of mind for a bit. 

Thanks @dalexj!! I wouldn't have even known it was broken if not for the PR >.<  Also, gave you a [shoutout on Twitter](https://twitter.com/josh_cheek/status/560120798913257473), but didn't tag you b/c I coudn't figure out what your handle was.

**Comment by dalexj** [comment]
if you need to tag me, minishguy on twitter

**Comment by jesperronn** [comment]
Nice work guys. My editor, for some reason, was stuck on version 1.4.1. I uninstalled, and reinstalled, which gave me the new version 1.5.

Thanks

**Comment by JoshCheek** [comment]
Looks like the config issues are still present (my post ultimately led to https://github.com/atom/settings-view/issues/356).

But the package is updated to fix all the non-config related deprecations, and v8's renaming of `String.contains` to `String.includes`, which made it always blow up >.<

**Pull request merged**
